import type { OutputResult, TypeInfo } from '../../shared/types';
import React from 'react';
import {
  BreadcrumbContainer,
  BreadcrumbItem,
  BreadcrumbSeparator,
  BreadcrumbWrapper,
  CodeContainer,
  CodeContent,
  CodeLine,
  Comment,
  EmptyState,
  Indent,
  Keyword,
  PanelHeader,
  PanelTitle,
  Punctuation,
  SourceLocation,
  TypeDocPanelContainer,
} from '../shared/styled';
import type { TypeDocLocale } from '../shared/locale';
import { en } from '../shared/locale';
import type { TypeRenderContext } from '../shared/types';
import {
  formatTypeDeclarationName,
  getBaseName,
} from '../shared/generic';
import { renderTypeNameWithGenerics } from './renderType';
import { renderDescription } from '../shared/renderDescription';
import { renderPropertyLine, renderUnionTypeView } from './renderView';
import { useTypeNavigation } from './hooks/useTypeNavigation';

export interface TypeDocPanelProps {
  /** Type key (corresponds to keys in the output JSON) */
  typeKey: string;
  /** Optional title prefix displayed before the type name */
  titlePrefix?: string;
  /** Type documentation data generated by react-type-doc */
  data: OutputResult | null;
  /** Locale for i18n, defaults to English */
  locale?: TypeDocLocale;
}

/**
 * 类型文档展示面板（代码编辑器风格）
 * 支持点击类型原地展开详情，通过面包屑导航返回
 */
const TypeDocPanel: React.FC<TypeDocPanelProps> = (props) => {
  const { typeKey, titlePrefix, data, locale = en } = props;

  const {
    reader,
    historyStack,
    currentTypeInfo,
    currentTitle,
    isInNestedView,
    handleTypeClick,
    navigateToLevel,
  } = useTypeNavigation(typeKey, titlePrefix, data, locale);

  // 括号点击状态管理
  const [clickedBracketId, setClickedBracketId] = React.useState<string | null>(
    null,
  );

  const handleBracketClick = React.useCallback((bracketId: string) => {
    setClickedBracketId((prev) => (prev === bracketId ? null : bracketId));
  }, []);

  if (!data || !reader) {
    return (
      <TypeDocPanelContainer>
        <EmptyState>{locale.dataNotLoaded}</EmptyState>
      </TypeDocPanelContainer>
    );
  }

  const typeInfo = reader.getRaw(typeKey);

  if (!typeInfo) {
    return (
      <TypeDocPanelContainer>
        <EmptyState>{locale.typeNotFound(typeKey)}</EmptyState>
      </TypeDocPanelContainer>
    );
  }

  const resolved = reader.resolveRef(typeInfo);

  /** 包含泛型参数的完整类型名（用于代码块的 interface 声明） */
  const rootDisplayName = resolved.genericParameters?.length
    ? formatTypeDeclarationName(
        reader.getDisplayName(resolved, typeKey),
        resolved.genericParameters,
      )
    : reader.getDisplayName(resolved, typeKey);

  /** 使用实际类型名构建显示标题（不含 registry key 中的路径前缀） */
  const rootDisplayTitle = titlePrefix
    ? `${titlePrefix} - ${rootDisplayName}`
    : rootDisplayName;

  const context: TypeRenderContext = {
    onTypeClick: handleTypeClick,
    reader,
    locale,
    onBracketClick: handleBracketClick,
    clickedBracketId,
  };

  if (resolved.kind === 'union' && !isInNestedView) {
    return (
      <TypeDocPanelContainer>
        <PanelHeader>
          <PanelTitle title={rootDisplayTitle}>{rootDisplayTitle}</PanelTitle>
        </PanelHeader>
        {renderUnionTypeView(rootDisplayName, typeInfo, context)}
      </TypeDocPanelContainer>
    );
  }

  const resolvedCurrentType = currentTypeInfo
    ? reader.resolveRef(currentTypeInfo)
    : null;
  const isNestedUnion = isInNestedView && resolvedCurrentType?.kind === 'union';

  const propEntries = reader.getPropertyEntries(
    isInNestedView ? currentTypeInfo! : typeInfo,
  );

  if (propEntries.length === 0 && resolved.kind !== 'union' && !isNestedUnion) {
    return (
      <TypeDocPanelContainer>
        <PanelHeader>
          <PanelTitle
            title={`${rootDisplayTitle} — ${locale.propertiesCount(0)}`}
          >
            {rootDisplayTitle} — {locale.propertiesCount(0)}
          </PanelTitle>
        </PanelHeader>
        <EmptyState>{locale.noProperties}</EmptyState>
      </TypeDocPanelContainer>
    );
  }

  const currentPropEntries = currentTypeInfo
    ? reader.getPropertyEntries(currentTypeInfo)
    : [];

  const displayTypeName = resolvedCurrentType
    ? resolvedCurrentType.genericParameters?.length
      ? formatTypeDeclarationName(
          reader.getDisplayName(resolvedCurrentType, currentTitle),
          resolvedCurrentType.genericParameters,
        )
      : reader.getDisplayName(resolvedCurrentType, currentTitle)
    : currentTitle;

  const panelTitleText = isInNestedView
    ? isNestedUnion
      ? getBaseName(displayTypeName)
      : `${getBaseName(displayTypeName)} — ${locale.propertiesCount(currentPropEntries.length)}`
    : `${rootDisplayTitle} — ${locale.propertiesCount(propEntries.length)}`;

  return (
    <TypeDocPanelContainer>
      <PanelHeader>
        <PanelTitle title={panelTitleText}>{panelTitleText}</PanelTitle>
      </PanelHeader>

      {/* 面包屑导航区域 */}
      <BreadcrumbWrapper $visible={isInNestedView}>
        <BreadcrumbContainer>
          <BreadcrumbItem
            $clickable
            title={rootDisplayTitle}
            onClick={() => navigateToLevel(-1)}
          >
            {rootDisplayTitle}
          </BreadcrumbItem>
          {historyStack.map((item, index) => (
            <React.Fragment key={index}>
              <BreadcrumbSeparator>›</BreadcrumbSeparator>
              <BreadcrumbItem
                $clickable={index < historyStack.length - 1}
                title={item.title}
                onClick={() => {
                  if (index < historyStack.length - 1) {
                    navigateToLevel(index);
                  }
                }}
              >
                {item.title}
              </BreadcrumbItem>
            </React.Fragment>
          ))}
        </BreadcrumbContainer>
      </BreadcrumbWrapper>

      <CodeContainer>
        <CodeContent>
          {isInNestedView ? (
            isNestedUnion ? (
              renderUnionTypeView(displayTypeName, currentTypeInfo!, context)
            ) : (
              <>
                <CodeLine>
                  <Keyword>interface</Keyword>
                  {renderTypeNameWithGenerics(
                    displayTypeName,
                    resolvedCurrentType?.genericParameters,
                  )}
                  <Punctuation>{'{'}</Punctuation>
                </CodeLine>

                {currentPropEntries.length > 0 ? (
                  currentPropEntries.map(
                    ([propName, propInfo]: [string, TypeInfo]) =>
                      renderPropertyLine(propName, propInfo, context),
                  )
                ) : (
                  <CodeLine>
                    <Indent $level={1} />
                    <Comment>{`// ${locale.noExpandableProperties}`}</Comment>
                  </CodeLine>
                )}

                <CodeLine>
                  <Punctuation>{'}'}</Punctuation>
                </CodeLine>
              </>
            )
          ) : (
            <>
              {resolved.description && (
                <CodeLine>
                  {renderDescription(
                    resolved.description,
                    0,
                    context,
                    resolved.descriptionLinks,
                  )}
                </CodeLine>
              )}
              <CodeLine>
                <Keyword>interface</Keyword>
                {renderTypeNameWithGenerics(
                  rootDisplayName,
                  resolved.genericParameters,
                )}
                <Punctuation>{'{'}</Punctuation>
              </CodeLine>

              {propEntries.map(([propName, propInfo]: [string, TypeInfo]) =>
                renderPropertyLine(propName, propInfo, context),
              )}

              <CodeLine>
                <Punctuation>{'}'}</Punctuation>
              </CodeLine>
            </>
          )}
        </CodeContent>

        {/* 源码位置 */}
        {isInNestedView && resolvedCurrentType?.sourceFile && (
          <SourceLocation>
            {'📍 '}
            {resolvedCurrentType.sourceFile}
            {resolvedCurrentType.sourceLine
              ? `:${resolvedCurrentType.sourceLine}`
              : ''}
          </SourceLocation>
        )}
      </CodeContainer>
    </TypeDocPanelContainer>
  );
};

export default TypeDocPanel;
